### ISSUE TITLE
Common datasource configuration format

### ISSUE THREAD

**Issue by frascuchon** [recognai/biome-text#15]
In order to standardize the datasource configuration format, i suggest a new yaml schema that i explain in next example:

```yaml
# Define de datasource source (implicitly give the ds format)
source: my/path/to/file.csv

# Extra attributes related to how to read the source
attributes:
   encoding: utf-8
   delimiter: ,
```

For file-based datasource, we could define a source as list of paths:

```yaml
source: 
- a/path/to/file.csv
- another/folder/containing/*.csv
```

 

This definition extends even for non file-based sources. An example should be:

```yaml
source: elasticsearch

attributes:
  es_host: https://elasticsearch.service:9200
  es_index: my-cool-index
  es_type: _docs
  query: { "query" : {"match_all" : {} }}
...
```

**Comment by dcfidalgo** [comment]
i like! :+1:

**Comment by dcfidalgo** [comment]
Do you think we need the `attributes` key? These can be absorbed as `kwargs` and the yml file would look like this:
```yml
# Define de datasource source (implicitly give the ds format)
source: my/path/to/file.csv

# Extra attributes related to how to read the source
encoding: utf-8
delimiter: ,
```

or

```yml
source: elasticsearch

es_host: https://elasticsearch.service:9200
es_index: my-cool-index
es_type: _docs
query: { "query" : {"match_all" : {} }}
```
