### ISSUE TITLE
Fix the usage of a metadata_file

### ISSUE THREAD

**Issue by dcfidalgo** [recognai/biome-text#3]
Does not work at the moment, i think the `ExamplePreparator` needs to be updated.

**Comment by dcfidalgo** [comment]
Maybe add this as an extra parameter to the datasource yml config file:

```yaml
forward:
  tokens: 
    source:
    - text
  gold_label:
    source: label
    mapping: label_mapping.txt
```

The source keyword should be omitted if the input of a forward parameter is just a string -> This should also be possible:
```yaml
forward:
  tokens: text  # or tokens: [text] 
  gold_label:
    source: label
    mapping: label_mapping.txt
```
